name: Daily Flake Check

on:
  schedule:
    # Run daily at 6 AM UTC
    - cron: '0 6 * * *'
  # Allow manual trigger
  workflow_dispatch:

jobs:
  flake-check:
    name: Daily Nix Flake Check
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      - name: Check Nix flake inputs
        uses: DeterminateSystems/flake-checker-action@v9
        with:
          fail-mode: true
